#include "../../Include/include.Community.global.h"
#include "/home/dalonso/C_pro/Demos_UTLs_CPGPLOT/include.CPG.global.h"
#include "../../Include/include.Output_Variables.global.h"
#include "../../Include/include.Parameter_Model.global.h"
#include "../../Include/include.PARAMETER_SPACE.global.h"
#include "../../Include/include.Stochastic_Realizations.global.h"
#include "../../Include/include.Time_Control.global.h"
#include "../../Include/include.Type_Model.global.h"
#include "../../Include/include.Power_Spectra_Control.global.h"
#include "../../Include/include.Initial_Conditions.global.h"
Parameter_Table * P_ARG; 
